version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the project...
      - npm run build
      - npm run export
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading artifacts to S3...
      - aws s3 sync out/ s3://your-bucket-name --acl public-read

artifacts:
  files:
    - '**/*'
  base-directory: out
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
